Repository geut/permanent-seeder, pull requests merged in 2020-11, with the labels that each got.

#132 fix: delete destroy storage
  CHANGELOG.md
  packages/cli/src/commands/key/remove-all.js
  packages/cli/src/commands/start.js
  packages/sdk/src/services/metrics.service.js
  packages/seeder/src/drive.js
  packages/seeder/src/seeder.js
Labels: seeder

#133 Update: switch to gh actions
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  .travis.yml
  README.md
  package.json
  packages/dashboard/src/components/DriveList.js
  packages/dashboard/src/components/HostStats.js
  packages/dashboard/src/components/NetworkIndicator.js
Labels: documentation

#134 Update: new release workflow pr and publish
  .github/workflows/publish.yml
  README.md
  package.json
Labels: documentation

#136 Release: 1.0.1
  CHANGELOG.md
  lerna.json
  package.json
  packages/cli/package.json
  packages/dashboard/package.json
  packages/sdk/package.json
  packages/seeder/package.json
Labels: release

#139 Fix for render
  packages/dashboard/src/components/HostStats.js
  packages/dashboard/src/components/NetworkIndicator.js
Labels: bug

#140 Release: 1.0.2
  CHANGELOG.md
  lerna.json
  packages/cli/package.json
  packages/dashboard/package.json
  packages/sdk/package.json
  packages/seeder/package.json
Labels: release

#142 Fix: remove bad deps (hooks)
  CHANGELOG.md
  packages/dashboard/src/components/DriveList.js
Labels: dashboard

#143 Release: 1.0.3
  CHANGELOG.md
  lerna.json
  packages/cli/package.json
  packages/dashboard/package.json
  packages/sdk/package.json
  packages/seeder/package.json
Labels: release

#144 Update: bump action version
  .github/workflows/publish.yml
Labels: actions

#145 Update: dashboard prepublish script
  CHANGELOG.md
  packages/dashboard/package.json
Labels: dashboard

#146 Release: 1.0.4
  CHANGELOG.md
  lerna.json
  packages/cli/package.json
  packages/dashboard/package.json
  packages/sdk/package.json
  packages/seeder/package.json
Labels: release

#147 Update: review publish action
  .github/workflows/publish.yml
  CHANGELOG.md
  package.json
  packages/cli/package.json
Labels: actions
